//! Exports the component catalog the website is generated from.
//!
//! ```sh
//! npm run generate:catalog
//! ```
//!
//! Writes `site/generated/catalog.json` from [`StoryId`] and the library
//! sources, replacing a hand-maintained list that could drift from the stories
//! it described. Event names are read out of `crates/gpui-ai/src` rather than
//! restated here, so a renamed event enum shows up as a catalog diff.

use gallery::{DECORATIONS_HEIGHT, HERO_HEIGHT, Overflow, StoryId, decoration_catalog};
use serde_json::{Map, Value, json};
use std::{fmt::Write as _, fs, path::PathBuf};

/// Every browser demo carries the same caveat; the native runtime is the one
/// that has been verified.
const LIMITATION: &str = "The live browser specimen requires WebGPU; the native component remains the authoritative runtime.";

/// The file every story's snippet markers live in, as the site should name it.
const SNIPPET_SOURCE: &str = "crates/gallery/src/gallery.rs";

/// And the file the decorations mark themselves in, which is their own.
const DECORATION_SOURCE: &str = "crates/gallery/src/decorations.rs";

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(std::path::Path::parent)
        .expect("the gallery crate lives two directories below the workspace root")
        .to_path_buf()
}

/// Reads the public event enums a component declares, in declaration order.
fn events(source: &str) -> Vec<String> {
    let mut found = Vec::new();
    for line in source.lines() {
        let trimmed = line.trim_start();
        let Some(rest) = trimmed.strip_prefix("pub enum ") else {
            continue;
        };
        let name: String = rest
            .chars()
            .take_while(|character| character.is_alphanumeric() || *character == '_')
            .collect();
        if name.ends_with("Event") {
            found.push(name);
        }
    }
    found
}

fn join_events(events: &[String]) -> String {
    match events {
        [] => String::new(),
        [only] => only.clone(),
        [rest @ .., last] => format!("{} and {last}", rest.join(", ")),
    }
}

/// Flattens generated prose into one Markdown-safe line.
fn markdown_text(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// Renders the consumer skill's component facts from the same values the site
/// receives. The authored skill carries selection judgment; this file carries
/// names, constructors, events, growth, and lineage that should never be
/// restated by hand.
fn component_skill_reference(components: &[Value], categories: &[Value]) -> String {
    let mut output = String::new();
    writeln!(
        output,
        "# gpui-ai component index\n\n\
         <!-- Generated by gallery-catalog-export from crates/gallery/src/story.rs. Do not edit. -->\n\n\
         Generated from the gpui-ai {} checkout. Resolve the consuming application's exact \
         gpui-ai revision before relying on a constructor: this index describes the checkout \
         that contains it, while an application may be pinned elsewhere.\n\n\
         Every component renders a snapshot supplied by the application and leaves durable \
         work, state transitions, and clocks with the application. Read `../state-events-and-progress.md` \
         for the ownership pattern and `../component-selection.md` for composition judgment.\n",
        env!("CARGO_PKG_VERSION")
    )
    .expect("writing Markdown to a String cannot fail");

    writeln!(output, "## Categories\n").expect("writing Markdown to a String cannot fail");
    for category in categories {
        let category = category
            .as_str()
            .expect("catalog categories must be strings");
        writeln!(
            output,
            "- [{category}](#{})",
            category.to_lowercase().replace(' ', "-")
        )
        .expect("writing Markdown to a String cannot fail");
    }

    for category in categories {
        let category = category
            .as_str()
            .expect("catalog categories must be strings");
        writeln!(output, "\n## {category}\n").expect("writing Markdown to a String cannot fail");

        for component in components
            .iter()
            .filter(|component| component["category"].as_str() == Some(category))
        {
            let slug = component["slug"]
                .as_str()
                .expect("catalog components must have slugs");
            let api = component["api"]
                .as_str()
                .expect("catalog components must have API types");
            let title = component["title"]
                .as_str()
                .expect("catalog components must have titles");
            let summary = markdown_text(
                component["summary"]
                    .as_str()
                    .expect("catalog components must have summaries"),
            );
            let usage = markdown_text(
                component["usage"]
                    .as_str()
                    .expect("catalog components must have usage expressions"),
            );
            let events = component["events"]
                .as_array()
                .expect("catalog component events must be an array")
                .iter()
                .map(|event| {
                    format!(
                        "`{}`",
                        event
                            .as_str()
                            .expect("catalog component events must be strings")
                    )
                })
                .collect::<Vec<_>>();
            let events = if events.is_empty() {
                "No component-specific event".to_owned()
            } else {
                events.join(", ")
            };
            let overflow = component["behavior"]["overflow"]
                .as_str()
                .expect("catalog components must describe overflow");
            let growth = if overflow.starts_with("Growing") {
                "vertical"
            } else {
                "wide"
            };
            let lineage = component["lineage"]["label"]
                .as_str()
                .expect("catalog components must describe lineage");
            let basis = component["lineage"]["basis"]
                .as_str()
                .expect("catalog lineage basis must be a string");
            let lineage = if basis.is_empty() {
                lineage.to_owned()
            } else {
                format!("{lineage} gpui-component `{basis}`")
            };
            let source = component["source"]
                .as_str()
                .expect("catalog components must name a source module");

            writeln!(
                output,
                "<!-- component:{slug} -->\n\
                 ### `{api}` — {title}\n\n\
                 - **Reach for it when:** {summary}\n\
                 - **Start with:** `{usage}`\n\
                 - **Intent:** {events}\n\
                 - **Growth:** {growth}; keep the final content reachable in a bounded host.\n\
                 - **Lineage:** {lineage}\n\
                 - **Source module:** `{source}`\n"
            )
            .expect("writing Markdown to a String cannot fail");
        }
    }

    if output.ends_with("\n\n") {
        output.pop();
    }

    output
}

/// Collects the code between `// snippet:start(<slug>[/<variant>])` and
/// `// snippet:end` markers, keyed by story slug then variant.
///
/// Snippets are cut from the gallery's own compiled source rather than written
/// beside it, so a story that changes shape cannot leave the website showing
/// code that no longer builds. A story may mark several regions for one
/// variant — an entity's construction and the place it is mounted, say — and
/// they are joined in source order.
fn snippets(source: &str) -> Vec<(String, String, String)> {
    type OpenSnippet<'a> = (Vec<(String, String)>, Vec<&'a str>);

    let mut collected: Vec<(String, String, String)> = Vec::new();
    let mut open: Option<OpenSnippet<'_>> = None;

    for line in source.lines() {
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix("// snippet:start(") {
            let keys = rest.strip_suffix(')').unwrap_or(rest);
            // Several keys for one region: the dither, the pop art, and the
            // engraving are one function with an argument, and each of their
            // pages should show it rather than a line pointing at it.
            let keys: Vec<(String, String)> = keys
                .split(',')
                .map(str::trim)
                .map(|key| {
                    let (slug, variant) = key.split_once('/').unwrap_or((key, "default"));
                    (slug.to_owned(), variant.to_owned())
                })
                .collect();
            assert!(!keys.is_empty(), "snippet:start names nothing");
            assert!(
                open.is_none(),
                "snippet:start inside an open snippet ({})",
                keys[0].0
            );
            open = Some((keys, Vec::new()));
            continue;
        }
        if trimmed == "// snippet:end" {
            let (keys, body) = open.take().expect("snippet:end without snippet:start");
            let indent = body
                .iter()
                .filter(|line| !line.trim().is_empty())
                .map(|line| line.len() - line.trim_start().len())
                .min()
                .unwrap_or(0);
            let code = body
                .iter()
                .map(|line| {
                    if line.len() > indent {
                        &line[indent..]
                    } else {
                        line.trim_start()
                    }
                })
                .collect::<Vec<_>>()
                .join("\n")
                .trim_end()
                .to_owned();
            assert!(!code.is_empty(), "{} marks an empty snippet", keys[0].0);

            for (slug, variant) in keys {
                match collected
                    .iter_mut()
                    .find(|(existing, existing_variant, _)| {
                        *existing == slug && *existing_variant == variant
                    }) {
                    Some((_, _, existing)) => {
                        existing.push_str("\n\n");
                        existing.push_str(&code);
                    }
                    None => collected.push((slug, variant, code.clone())),
                }
            }
            continue;
        }
        if let Some((_, body)) = open.as_mut() {
            body.push(line);
        }
    }

    assert!(open.is_none(), "a snippet was opened and never closed");
    collected
}

fn main() {
    let root = workspace_root();
    let mut components = Vec::new();

    for (index, story) in StoryId::ALL.iter().enumerate() {
        let meta = story
            .meta()
            .unwrap_or_else(|| panic!("{} has no catalog metadata", story.slug()));

        let source = format!("crates/gpui-ai/src/{}.rs", meta.module);
        let text = fs::read_to_string(root.join(&source))
            .unwrap_or_else(|error| panic!("cannot read {source}: {error}"));
        assert!(
            text.contains(&format!("pub struct {}", meta.api)),
            "{source} does not declare pub struct {}",
            meta.api
        );

        let events = events(&text);
        let interaction = if events.is_empty() {
            "This presentation surface adds no component-specific interaction event.".to_owned()
        } else {
            format!(
                "Interactive intent is reported through the typed {} contract{} and stable application IDs.",
                join_events(&events),
                if events.len() > 1 { "s" } else { "" }
            )
        };
        let overflow = match meta.overflow {
            Overflow::Vertical => {
                "Growing content remains reachable in a bounded vertical surface; reduced motion preserves a useful state."
            }
            Overflow::Wide => {
                "Wide content retains context in a bounded surface; reduced motion preserves a useful state."
            }
        };

        let variants: Vec<Value> = story
            .variants()
            .iter()
            .map(|(id, label)| json!({ "id": id, "label": label }))
            .collect();

        components.push(json!({
            "sequence": index + 1,
            "slug": story.slug(),
            "title": story.title(),
            "compactLabel": story.title(),
            "category": meta.category,
            "summary": meta.summary,
            "source": source,
            "api": meta.api,
            // What a reader deciding between this library and the one it is
            // built on needs per component, rather than only in prose
            // somewhere else: where it stands, what it stands on, and why it
            // is here.
            "lineage": {
                "kind": meta.lineage.id(),
                "label": meta.lineage.label(),
                "basis": meta.lineage_basis,
                "note": meta.lineage_note,
            },
            "usage": meta.usage,
            "height": meta.height,
            // The window frame the site draws around each demo.
            "windowTitle": format!("{} — gpui-ai", story.title()),
            "variants": variants,
            "events": events,
            "event": events.first().cloned(),
            "limitation": LIMITATION,
            "behavior": {
                "ownership": format!(
                    "{} renders state supplied by the application; it does not own durable work.",
                    meta.api
                ),
                "interaction": interaction,
                "semantics": meta.summary,
                "overflow": overflow,
            },
        }));
    }

    let mut categories = Vec::new();
    for component in &components {
        let category = component["category"].clone();
        if !categories.contains(&category) {
            categories.push(category);
        }
    }
    let skill_reference = component_skill_reference(&components, &categories);

    // The hero is addressable like any story but is not a component, so it
    // sits beside `components` rather than inside it: every consumer counting
    // or listing the catalog would otherwise have to filter it out.
    let hero = StoryId::GuidedDemo;
    assert!(
        hero.meta().is_none(),
        "the hero is not a catalog component and must carry no component metadata"
    );
    assert!(
        !StoryId::ALL.contains(&hero),
        "the hero must stay out of the component index"
    );

    let mut document = Map::new();
    document.insert(
        "$comment".to_owned(),
        Value::String(
            "Generated by gallery-catalog-export from crates/gallery/src/story.rs. Do not edit."
                .to_owned(),
        ),
    );
    document.insert(
        "hero".to_owned(),
        json!({
            "slug": hero.slug(),
            "title": hero.title(),
            "height": HERO_HEIGHT,
            "windowTitle": format!("{} — gpui-ai", hero.title()),
            "siteOnly": true,
        }),
    );
    // Decorations are not components and never will be: they are what an
    // application paints into a component, and the site documents them as
    // their own section. Generated from the gallery's own list, so one added
    // in Rust becomes a page.
    let decorations: Vec<Value> = decoration_catalog()
        .into_iter()
        .map(|(slug, label, note)| json!({ "slug": slug, "label": label, "note": note }))
        .collect();
    document.insert(
        "effects".to_owned(),
        json!({
            "story": StoryId::Decorations.slug(),
            "height": DECORATIONS_HEIGHT,
            "windowTitle": format!("{} - gpui-ai", StoryId::Decorations.title()),
            "source": "crates/gallery/src/decorations.rs",
            "decorations": decorations,
        }),
    );
    document.insert("categories".to_owned(), Value::Array(categories));
    document.insert("components".to_owned(), Value::Array(components));
    // The one file every snippet is cut from. A component's own `source` is
    // where the type is implemented, which is a different file and a different
    // claim: the site shows this above the code so that what it says the code
    // came from is where the code came from.
    document.insert(
        "snippetSource".to_owned(),
        Value::String(SNIPPET_SOURCE.to_owned()),
    );

    let output_root = std::env::var_os("GPUI_AI_OUTPUT_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.clone());
    let output = output_root.join("site").join("generated");
    fs::create_dir_all(&output).expect("site/generated must be writable");
    let path = output.join("catalog.json");
    let rendered = format!(
        "{}\n",
        serde_json::to_string_pretty(&Value::Object(document)).expect("the catalog must serialize")
    );
    fs::write(&path, rendered).expect("the catalog must be writable");

    let mut marked = Vec::new();
    for source in [SNIPPET_SOURCE, DECORATION_SOURCE] {
        let text = fs::read_to_string(root.join(source))
            .unwrap_or_else(|error| panic!("cannot read {source}: {error}"));
        marked.extend(snippets(&text));
    }
    let mut by_story: Map<String, Value> = Map::new();
    for (slug, variant, code) in marked {
        assert!(
            slug.parse::<StoryId>().is_ok(),
            "snippet marker names {slug}, which is not a story"
        );
        by_story
            .entry(slug)
            .or_insert_with(|| Value::Object(Map::new()))
            .as_object_mut()
            .expect("snippet entries are objects")
            .insert(variant, Value::String(code));
    }

    for story in StoryId::ALL {
        assert!(
            by_story.contains_key(story.slug()),
            "{} has no // snippet:start marker; every component page needs one",
            story.slug()
        );
    }

    let mut snippet_document = Map::new();
    snippet_document.insert(
        "$comment".to_owned(),
        Value::String(
            "Generated by gallery-catalog-export from the gallery's own source. Do not edit."
                .to_owned(),
        ),
    );
    snippet_document.insert("snippets".to_owned(), Value::Object(by_story));
    fs::write(
        output.join("snippets.json"),
        format!(
            "{}\n",
            serde_json::to_string_pretty(&Value::Object(snippet_document))
                .expect("the snippets must serialize")
        ),
    )
    .expect("the snippets must be writable");

    let skill_output = output_root
        .join("skills")
        .join("gpui-ai")
        .join("references")
        .join("generated");
    fs::create_dir_all(&skill_output).expect("the generated skill directory must be writable");
    fs::write(skill_output.join("components.md"), skill_reference)
        .expect("the generated skill component index must be writable");

    println!(
        "generated site catalog, snippets, and skill component index: {} components",
        StoryId::ALL.len()
    );
}
